# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: notes-configmap
  namespace: notes
data:
  TZ: UTC
  TRILIUM_UID: "1000"
  TRILIUM_GID: "1000"
  TRILIUM_DATA_DIR: "/home/trilium/trilium-data"
---

