apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      # securityContext:
      #   fsGroup: 33
      #   runAsUser: 33
      #   runAsGroup: 33
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: audiobookshelf-configmap
                  key: PORT
          ports:
            - containerPort: 3005
      volumeMounts:
        - name: audiobooks-data
          mountPath: /etc/audiobookshelf/data/audiobooks
        - name: podcasts-data
          mountPath: /etc/audiobookshelf/data/podcasts
        - name: config-data
          mountPath: /config
        - name: metadata-data
          mountPath: /metadata
   #     securityContext:
      #       allowPrivilegeEscalation: false
      envFrom:
        - configMapRef: 
          name: audiobookshelf-configmap
        # - secretRef:
        #     name: audiobookshelf-container-env
      volumes:
        - name: audiobooks-data
          persistentVolumeClaim:
            claimName: audiobooks-data-pvc
        - name: podcasts-data
          persistentVolumeClaim:
            claimName: podcasts-data-pvc
        - name: config-data
          persistentVolumeClaim:
            claimName: config-data-pvc
        - name: metadata-data
          persistentVolumeClaim:
            claimName: metadata-data-pvc


